name: Newman Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html
      
      - name: Run Newman tests
        run: newman run scriptexamples.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export testReport.html
        
