name: Newman Test Run
on:
  push:
    branches:
    - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
            collection: scriptexamples.postman_collection.json
            reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
    
