name: Newman Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html
      
      - name: Run Newman tests
        run: scriptexamples.postman_collection.json -r html,cli
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: newman/*.html
