name: Newman Test Run
on:
  push:
    branches:
    - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install newman 
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for test results
        run: mkdir -p testResults


      - name: Running collectgion
        run: |
          newman run scriptexamples.postman_collection.json -r htmlextra --reporter-htmlextra-export report.html
      - name: output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
